# SPDX-FileCopyrightText: 2020 Stefan Adams <stefan.adams@vipcomag.de>
# SPDX-License-Identifier: GPL-2.0


EXTRA_CFLAGS = -I$(ZTOP)/kernel/sel4/build_64_sel4zsipos/libpicotcpng/picotcp_external/picotcp/build/include

obj-y := sel4ip.o iprcchan.o remcalls_m.o af_inet.o doioctl.o proc.o

